name: Node.js Compatibility

on:
  schedule:
    # Run weekly to check compatibility with latest Node.js versions
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  test-node-versions:
    name: Test Node.js Compatibility
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [18.19.0, 18.x, 20.x]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
      continue-on-error: ${{ matrix.node-version != '18.19.0' }}

    - name: Test basic functionality
      run: |
        # Start server
        npm start &
        SERVER_PID=$!
        sleep 5
        
        # Test endpoints
        curl -f http://localhost:8080/health
        curl -f http://localhost:8080/
        
        # Cleanup
        kill $SERVER_PID

  report-compatibility:
    name: Report Compatibility Results
    runs-on: ubuntu-latest
    needs: [test-node-versions]
    if: always()
    
    steps:
    - name: Report Results
      run: |
        echo "Node.js compatibility test completed"
        echo "Check individual job results for detailed information"